//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileTransfer;

/** @hidden */
public class _TransferPrxI extends com.zeroc.Ice._ObjectPrxI implements TransferPrx
{
    /** @hidden */
    public static final long serialVersionUID = 0L;
}
