//
// Copyright (c) ZeroC, Inc. All rights reserved.
//
//
// Ice version 3.7.10
//
// <auto-generated>
//
// Generated from file `FileTransfer.ice'
//
// Warning: do not edit this file.
//
// </auto-generated>
//

package FileTransfer;

public interface TransferPrx extends com.zeroc.Ice.ObjectPrx
{
    default String negotiateKey(String clientPublicKey)
    {
        return negotiateKey(clientPublicKey, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String negotiateKey(String clientPublicKey, java.util.Map<String, String> context)
    {
        return _iceI_negotiateKeyAsync(clientPublicKey, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> negotiateKeyAsync(String clientPublicKey)
    {
        return _iceI_negotiateKeyAsync(clientPublicKey, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> negotiateKeyAsync(String clientPublicKey, java.util.Map<String, String> context)
    {
        return _iceI_negotiateKeyAsync(clientPublicKey, context, false);
    }

    /**
     * @hidden
     * @param iceP_clientPublicKey -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_negotiateKeyAsync(String iceP_clientPublicKey, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "negotiateKey", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_clientPublicKey);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    default void sendFile(String fileName, byte[] fileContent)
    {
        sendFile(fileName, fileContent, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default void sendFile(String fileName, byte[] fileContent, java.util.Map<String, String> context)
    {
        _iceI_sendFileAsync(fileName, fileContent, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<Void> sendFileAsync(String fileName, byte[] fileContent)
    {
        return _iceI_sendFileAsync(fileName, fileContent, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<Void> sendFileAsync(String fileName, byte[] fileContent, java.util.Map<String, String> context)
    {
        return _iceI_sendFileAsync(fileName, fileContent, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileName -
     * @param iceP_fileContent -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<Void> _iceI_sendFileAsync(String iceP_fileName, byte[] iceP_fileContent, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<Void> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "sendFile", null, sync, null);
        f.invoke(false, context, null, ostr -> {
                     ostr.writeString(iceP_fileName);
                     ostr.writeByteSeq(iceP_fileContent);
                 }, null);
        return f;
    }

    default String receiveHash(String fileHash)
    {
        return receiveHash(fileHash, com.zeroc.Ice.ObjectPrx.noExplicitContext);
    }

    default String receiveHash(String fileHash, java.util.Map<String, String> context)
    {
        return _iceI_receiveHashAsync(fileHash, context, true).waitForResponse();
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> receiveHashAsync(String fileHash)
    {
        return _iceI_receiveHashAsync(fileHash, com.zeroc.Ice.ObjectPrx.noExplicitContext, false);
    }

    default java.util.concurrent.CompletableFuture<java.lang.String> receiveHashAsync(String fileHash, java.util.Map<String, String> context)
    {
        return _iceI_receiveHashAsync(fileHash, context, false);
    }

    /**
     * @hidden
     * @param iceP_fileHash -
     * @param context -
     * @param sync -
     * @return -
     **/
    default com.zeroc.IceInternal.OutgoingAsync<java.lang.String> _iceI_receiveHashAsync(String iceP_fileHash, java.util.Map<String, String> context, boolean sync)
    {
        com.zeroc.IceInternal.OutgoingAsync<java.lang.String> f = new com.zeroc.IceInternal.OutgoingAsync<>(this, "receiveHash", null, sync, null);
        f.invoke(true, context, null, ostr -> {
                     ostr.writeString(iceP_fileHash);
                 }, istr -> {
                     String ret;
                     ret = istr.readString();
                     return ret;
                 });
        return f;
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TransferPrx checkedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, ice_staticId(), TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Contacts the remote server to verify that the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TransferPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, context, ice_staticId(), TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TransferPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, ice_staticId(), TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Contacts the remote server to verify that a facet of the object implements this type.
     * Raises a local exception if a communication error occurs.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @param context The Context map to send with the invocation.
     * @return A proxy for this type, or null if the object does not support this type.
     **/
    static TransferPrx checkedCast(com.zeroc.Ice.ObjectPrx obj, String facet, java.util.Map<String, String> context)
    {
        return com.zeroc.Ice.ObjectPrx._checkedCast(obj, facet, context, ice_staticId(), TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @return A proxy for this type.
     **/
    static TransferPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Downcasts the given proxy to this type without contacting the remote server.
     * @param obj The untyped proxy.
     * @param facet The name of the desired facet.
     * @return A proxy for this type.
     **/
    static TransferPrx uncheckedCast(com.zeroc.Ice.ObjectPrx obj, String facet)
    {
        return com.zeroc.Ice.ObjectPrx._uncheckedCast(obj, facet, TransferPrx.class, _TransferPrxI.class);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the per-proxy context.
     * @param newContext The context for the new proxy.
     * @return A proxy with the specified per-proxy context.
     **/
    @Override
    default TransferPrx ice_context(java.util.Map<String, String> newContext)
    {
        return (TransferPrx)_ice_context(newContext);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the adapter ID.
     * @param newAdapterId The adapter ID for the new proxy.
     * @return A proxy with the specified adapter ID.
     **/
    @Override
    default TransferPrx ice_adapterId(String newAdapterId)
    {
        return (TransferPrx)_ice_adapterId(newAdapterId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoints.
     * @param newEndpoints The endpoints for the new proxy.
     * @return A proxy with the specified endpoints.
     **/
    @Override
    default TransferPrx ice_endpoints(com.zeroc.Ice.Endpoint[] newEndpoints)
    {
        return (TransferPrx)_ice_endpoints(newEndpoints);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator cache timeout.
     * @param newTimeout The new locator cache timeout (in seconds).
     * @return A proxy with the specified locator cache timeout.
     **/
    @Override
    default TransferPrx ice_locatorCacheTimeout(int newTimeout)
    {
        return (TransferPrx)_ice_locatorCacheTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the invocation timeout.
     * @param newTimeout The new invocation timeout (in seconds).
     * @return A proxy with the specified invocation timeout.
     **/
    @Override
    default TransferPrx ice_invocationTimeout(int newTimeout)
    {
        return (TransferPrx)_ice_invocationTimeout(newTimeout);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for connection caching.
     * @param newCache <code>true</code> if the new proxy should cache connections; <code>false</code> otherwise.
     * @return A proxy with the specified caching policy.
     **/
    @Override
    default TransferPrx ice_connectionCached(boolean newCache)
    {
        return (TransferPrx)_ice_connectionCached(newCache);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the endpoint selection policy.
     * @param newType The new endpoint selection policy.
     * @return A proxy with the specified endpoint selection policy.
     **/
    @Override
    default TransferPrx ice_endpointSelection(com.zeroc.Ice.EndpointSelectionType newType)
    {
        return (TransferPrx)_ice_endpointSelection(newType);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for how it selects endpoints.
     * @param b If <code>b</code> is <code>true</code>, only endpoints that use a secure transport are
     * used by the new proxy. If <code>b</code> is false, the returned proxy uses both secure and
     * insecure endpoints.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TransferPrx ice_secure(boolean b)
    {
        return (TransferPrx)_ice_secure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the encoding used to marshal parameters.
     * @param e The encoding version to use to marshal request parameters.
     * @return A proxy with the specified encoding version.
     **/
    @Override
    default TransferPrx ice_encodingVersion(com.zeroc.Ice.EncodingVersion e)
    {
        return (TransferPrx)_ice_encodingVersion(e);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its endpoint selection policy.
     * @param b If <code>b</code> is <code>true</code>, the new proxy will use secure endpoints for invocations
     * and only use insecure endpoints if an invocation cannot be made via secure endpoints. If <code>b</code> is
     * <code>false</code>, the proxy prefers insecure endpoints to secure ones.
     * @return A proxy with the specified selection policy.
     **/
    @Override
    default TransferPrx ice_preferSecure(boolean b)
    {
        return (TransferPrx)_ice_preferSecure(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the router.
     * @param router The router for the new proxy.
     * @return A proxy with the specified router.
     **/
    @Override
    default TransferPrx ice_router(com.zeroc.Ice.RouterPrx router)
    {
        return (TransferPrx)_ice_router(router);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for the locator.
     * @param locator The locator for the new proxy.
     * @return A proxy with the specified locator.
     **/
    @Override
    default TransferPrx ice_locator(com.zeroc.Ice.LocatorPrx locator)
    {
        return (TransferPrx)_ice_locator(locator);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for collocation optimization.
     * @param b <code>true</code> if the new proxy enables collocation optimization; <code>false</code> otherwise.
     * @return A proxy with the specified collocation optimization.
     **/
    @Override
    default TransferPrx ice_collocationOptimized(boolean b)
    {
        return (TransferPrx)_ice_collocationOptimized(b);
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses twoway invocations.
     * @return A proxy that uses twoway invocations.
     **/
    @Override
    default TransferPrx ice_twoway()
    {
        return (TransferPrx)_ice_twoway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses oneway invocations.
     * @return A proxy that uses oneway invocations.
     **/
    @Override
    default TransferPrx ice_oneway()
    {
        return (TransferPrx)_ice_oneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch oneway invocations.
     * @return A proxy that uses batch oneway invocations.
     **/
    @Override
    default TransferPrx ice_batchOneway()
    {
        return (TransferPrx)_ice_batchOneway();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses datagram invocations.
     * @return A proxy that uses datagram invocations.
     **/
    @Override
    default TransferPrx ice_datagram()
    {
        return (TransferPrx)_ice_datagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, but uses batch datagram invocations.
     * @return A proxy that uses batch datagram invocations.
     **/
    @Override
    default TransferPrx ice_batchDatagram()
    {
        return (TransferPrx)_ice_batchDatagram();
    }

    /**
     * Returns a proxy that is identical to this proxy, except for compression.
     * @param co <code>true</code> enables compression for the new proxy; <code>false</code> disables compression.
     * @return A proxy with the specified compression setting.
     **/
    @Override
    default TransferPrx ice_compress(boolean co)
    {
        return (TransferPrx)_ice_compress(co);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection timeout setting.
     * @param t The connection timeout for the proxy in milliseconds.
     * @return A proxy with the specified timeout.
     **/
    @Override
    default TransferPrx ice_timeout(int t)
    {
        return (TransferPrx)_ice_timeout(t);
    }

    /**
     * Returns a proxy that is identical to this proxy, except for its connection ID.
     * @param connectionId The connection ID for the new proxy. An empty string removes the connection ID.
     * @return A proxy with the specified connection ID.
     **/
    @Override
    default TransferPrx ice_connectionId(String connectionId)
    {
        return (TransferPrx)_ice_connectionId(connectionId);
    }

    /**
     * Returns a proxy that is identical to this proxy, except it's a fixed proxy bound
     * the given connection.@param connection The fixed proxy connection.
     * @return A fixed proxy bound to the given connection.
     **/
    @Override
    default TransferPrx ice_fixed(com.zeroc.Ice.Connection connection)
    {
        return (TransferPrx)_ice_fixed(connection);
    }

    static String ice_staticId()
    {
        return "::FileTransfer::Transfer";
    }
}
